### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by marksantcroos** [iljah/hdintegrator#1]
Is there a reason not to provide a pypi package?
I generally consider that a good practice.

**Comment by iljah** [comment]
If I understand correctly, pypi uses python distutils to do the work but the first problem is that distutils doesn't seem to support building C++ executables. After following the documentation for extensions it only builds a .o file and I haven't found a way to convince it to create an executable that would be installed somewhere. At this point I think pypi installation will have to exclude non-python integrands...

**Comment by iljah** [comment]
Fixed by https://github.com/iljah/hdintegrator/commit/05efc047b61def32645545dcee763f750b4eb476 and later commits as best as possible I think. If you know of a way to get setuptools to compile and install executables along with python code feel free to reopen. The version obtained from pip includes integrand(s) implemented in python.

**Comment by marksantcroos** [comment]
Thanks!
